app:
  base-uri: http://localhost:5666

custom:
  security:
    # 服务器网络地址
    host: http://localhost

#logging:
#  level:
#    # root：根记录器，用于分配默认日志记录级别。
#    root: debug

spring:
  data:
    redis:
      # redis 服务器主机
      host: turing-redis
      # redis 密码
      password: password
  datasource:
    # 数据库的 JDBC URL。
    url: jdbc:postgresql://turing-db:5432/turing
    # 数据库的登录用户名。
    username: turing
    # 数据库的登录密码。
    password: password
  jpa:
    hibernate:
      # DDL 模式。这实际上是“hibernate.hbm2ddl.auto”属性的快捷方式。
      # 当使用嵌入式数据库且未检测到模式管理器时，默认为“create-drop”。否则，默认为“none”。
      ddl-auto: none