custom:
  security:
    # 服服务器网络地址
    host:

spring:
  data:
    redis:
      # redis 服务器主机
      host:
      # redis 密码
      password:
  datasource:
    # 数据库的 JDBC URL。
    url:
    # 数据库的登录用户名。
    username:
    # 数据库的登录密码。
    password:
  jpa:
    hibernate:
      # DDL 模式。这实际上是“hibernate.hbm2ddl.auto”属性的快捷方式。
      # 当使用嵌入式数据库且未检测到模式管理器时，默认为“create-drop”。否则，默认为“none”。
      ddl-auto: none