[versions]
org-springframework-boot = "4.0.1"
io-spring-dependency-management = "1.1.7"
io-spring-javaformat = "0.0.47"
org-graalvm-buildtools-native = "0.11.3"
org-jetbrains-kotlin = "2.3.0"
java-language = "25"
com-github-therapi-runtime-javadoc = "0.15.0"
de-codecentric-spring-boot-admin-dependencies = "3.5.6"
org-apache-poi-poi = "5.4.1"
org-springdoc = "3.0.1"

[libraries]
com-github-therapi-therapi-runtime-javadoc-scribe = { module = "com.github.therapi:therapi-runtime-javadoc-scribe", version.ref = "com-github-therapi-runtime-javadoc" }
com-github-therapi-therapi-runtime-javadoc = { module = "com.github.therapi:therapi-runtime-javadoc", version.ref = "com-github-therapi-runtime-javadoc" }
de-codecentric-spring-boot-admin-dependencies = { module = "de.codecentric:spring-boot-admin-dependencies", version.ref = "de-codecentric-spring-boot-admin-dependencies" }
org-apache-poi-poi = { module = "org.apache.poi:poi", version.ref = "org-apache-poi-poi" }
org-springdoc-springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "org-springdoc" }
org-springdoc-springdoc-openapi-starter-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "org-springdoc" }
org-springdoc-springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "org-springdoc" }

[plugins]